Fixed "can't convert Array into String" error on install
This fixes the following error when installing gimli via gem
when gems like `gem-ctags` or `rdoc` are already installed:

    ERROR:  While executing gem ... (TypeError)
        can't convert Array into String

This is because `require_path=` accepts a string, not an array.
However, `require_paths=` accepts an array.